def hello():
    name = "world"
    msg = "hi"
    print(msg, name)
    print("edit1")
    print("edit2")
    print("edit3")
    print("edit4")
    print("edit5")
    print("edit6")
    print("edit7")
    print("edit8")
    print("edit9")
    print("edit10")
    print("edit11")
    print("edit12")
    print("edit13")
    print("edit14")
    print("edit15")
    print("edit16")
    print("edit17")
    print("edit18")
    print("edit19")
    print("edit20")
    print("edit21")
    print("edit22")
    print("edit23")
    print("edit24")
    print("edit25")
    print("edit26")
    print("edit27")
    print("edit28")
    print("edit29")
    print("edit30")
    print("edit31")
    print("edit32")
    print("edit33")
    print("edit34")
    print("edit35")
    print("edit36")
    print("edit37")
    print("edit38")
    print("edit39")
    print("edit40")
    print("edit41")
    print("edit42")
    print("edit43")
    print("edit44")
    print("edit45")
    print("edit46")
    print("edit47")
    print("edit48")
    print("edit49")
    print("edit50")
    return msg
